name: Deploy Frontend to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Create .env file from secrets
        working-directory: frontend
        run: |
          echo "BACKEND_URL=${{ secrets.BACKEND_URL }}" > .env

      - name: Install dependencies
        working-directory: frontend
        run: npm install

      - name: Run build and Webpack
        working-directory: frontend
        run: |
          npm run build
          npx webpack --mode production

      - name: Extract projectId from firebase.json
        id: project_id
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > sa.json
          echo "PROJECT_ID=$(jq -r .project_id sa.json)" >> $GITHUB_ENV

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: ${{ env.PROJECT_ID }}
