name: Deploy Frontend to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Create .env file from secrets
        working-directory: frontend
        run: |
          echo "BACKEND_URL=${{ secrets.BACKEND_URL }}" > .env

      - name: Install dependencies
        working-directory: frontend
        run: npm install

      - name: Run build and Webpack
        working-directory: frontend
        run: |
          npm run build
          npx webpack --mode production

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        working-directory: frontend
        run: firebase deploy --only hosting --project ${{ secrets.FIREBASE_PROJECT_ID }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
